#!/usr/bin/env bash
# Installs Nginx web server on the server
#+ Nginx should be listening to port 80
#+ When querying nginx at it's root using curl it
#+	must return a page with a sting "Hello World!"
#+ configures a new Ubuntu machine to respect above requirement
# installs nginx and configures it on a remote server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World' > /var/www/html/index.nginx-debian.html
service nginx start
