#!/usr/bin/env bash
# Installs and configures HAproxy with version 1.5 or greater
#+ in order to send trafic to web-01 and web-02
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  AAbdul-alx_front
        bind *:80
        mode http
        default_backend AAbdul-alx_back
backend Ahmad-alx_back
        balance roundrobin
        server 6369-web-01 35.168.112.100:80 check
        server 6369-web-02 3.234.244.180:80 check
"
 echo "$server_config" >> /etc/haproxy/haproxy.cfg

 echo "ENABLED=1" >> /etc/default/haproxy

 sudo service haproxy restart
