#!/usr/bin/env bash
# prints numbers from 1 to 100
# prints FizzBuzz when the number is a multiple of 3 and 5
# prints Fizz when a number is a multiple of 3
# prints Buzz when a number is a multiple of 5

i=1
while [ $i -lt 101 ]
do
    if [ $(( i%15 )) = 0 ]
    then
        echo "FizzBuzz"
    elif [ $(( i%3 )) = 0 ]
    then
        echo "Fizz"
    elif [ $(( i%5 )) = 0 ]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
    (( i++ ))
done
